// +build !arm
// +build !wasm
// Code generated by ObjectBox; DO NOT EDIT.

package model

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(5)

	model.RegisterBinding(ProbeBinding)
	model.RegisterBinding(TemperatureRecordBinding)
	model.LastEntityId(2, 5287188735980611158)

	return model
}
